/* 
**  mod_url_alias.c -- Apache sample url_alias module
**  [Autogenerated via ``apxs -n url_alias -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_url_alias.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /url_alias in as follows:
**
**    #   httpd.conf
**    LoadModule url_alias_module modules/mod_url_alias.so
**    <Location /url_alias>
**    SetHandler url_alias
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /url_alias and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/url_alias 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_url_alias.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int url_alias_handler(request_rec *r)
{
    if (strcmp(r->handler, "url_alias")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_url_alias.c\n", r);
    return OK;
}

static void url_alias_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(url_alias_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA url_alias_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    url_alias_register_hooks  /* register hooks                      */
};

